services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - ollama-net
  
  ollama-init:
    container_name: ollama-init
    image: curlimages/curl:latest
    depends_on:
      - ollama
    volumes:
      - ./scripts:/scripts
    entrypoint: /bin/sh
    command: -c "/scripts/pull-models.sh"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - DEFAULT_MODEL=gemma3
    networks:
      - ollama-net
  
  blazor:
    container_name: chat-blazor
    image: chat-blazor:latest
    depends_on:
      - ollama
      - ollama-init
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - Ollama__BaseUrl=http://ollama:11434
    restart: unless-stopped
    networks:
      - ollama-net

volumes:
  ollama:

networks:
  ollama-net:
    driver: bridge